version: '2'

services:
    nginx:
        image: nginx:1.13.3
        ports:
            - 8001:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - ./public:/var/www/html

    mysql:
        image: mysql:8.0.2
        ports:
            - 3306:3306
        volumes:
            - ~/.backup/mysql/article:/var/lib/mysql

        environment:
            - "MYSQL_ROOT_PASSWORD=my-mysql-password"
            - "MYSQL_DATABASE=medium-article-db"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8002:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql

